---
title: "Test"
editor: visual
format: html
---

### Methods

HB 2160 would increase community and housing development capacity by requiring cities to adopt maximum FAR requirements no more restrictive than those specified in the bill. While some cities use maximum FAR to regulate development, many cities use other measures, the most common of which is a combination of maximum building height and maximum lot coverage. In order to accurately compare development capacity across the study area, we create a standardized measurement of development capacity which we define as follows:

$$
\text{SDC}_i = 
\begin{cases} 
\text{FAR}_i & \text{if parcel } i \text{ uses FAR} \\
(\text{MBF}_i \times \text{MLC%}_i) & \text{if parcel } i \text{ does not use FAR}
\end{cases}
$$ {#eq-sdc}

Where:

-   $\text{SDC}_i$: Standardized Development Capacity for parcel $i$

-   $\text{FAR}_i$: Floor Area Ratio for parcel $i$

-   $\text{MBF}_i$: Maximum Building Floors for parcel $i$

-   $\text{MLC%}_i$: Maximum Lot Coverage Percentage for parcel $i$

We use net development capacity (${NDC}$) to represent the effect of the bill on development capacity at the scale of individual tax parcels. We define ${NDC}$ as follows:

$$
NDC_i = SDC_{new,i} - SDC_{old,i}
$$ {#eq-ndc} Where:

-   $SDC_{old,i}$: parcel $i$'s current (standarized) maximum development capacity.
-   $SDC_{new,i}$: the (standardized) maximum development capacity that would apply to parcel $i$ if HB 2160 became law.

To quantify the impact of the proposed bill on a geographic scale larger than an individual parcel, we employ two metrics: an absolute metric, the total net development capacity ($T_{NDC}$), and a relative metric, the area-weighted mean of net development capacity ($AWM_{NDC}$).

#### Total Net Development Capacity ($T_{NDC}$)

The total net development capacity ($T_{NDC}$) is calculated as the sum of the net development capacity for each parcel, adjusted by the parcel's area and eligibility based on specific criteria. We define it as follows:

$$
T_{NDC} = \sum_{i}(NDC_i \cdot A_i \cdot I_i)
$$

Where:

-   $NDC_i$: the net development capacity for parcel $i$.
-   $A_i$: the geometric area of parcel $i$.
-   $I_i$: an indicator function that equals 1 if parcel $i$ satisfies all of the following conditions: it is within a station area, it lies within a zoning district where residential use is permitted, and it is within an urban growth area; otherwise, $I_i$ equals 0.

This formula ensures that only parcels meeting all specified conditions contribute to the total net development capacity. The indicator function ($I_i$) serves as a filter, excluding parcels not suited for development under the proposed bill's guidelines.

#### Area-Weighted Mean of Net Development Capacity ($AWM_{NDC}$)

To calculate the mean net development capacity, weighted by the proportion of the area that each parcel occupies within the eligible region, we use the following formula::

$$
AWM_{NDC} = \frac{\sum_{i}(NDC_i \cdot A_i \cdot I_i)}{\sum_{i}(A_i \cdot I_i)}
$$ {#eq-awm-ndc}

This calculation divides the sum of the net development capacity of each parcel, adjusted by its area and eligibility, by the total eligible area. This method results in a weighted mean that reflects the proportional impact of each parcel, with larger parcels having a greater influence on the overall metric.

Our method offers metrics for evaluating changes in development capacity, reflecting the effects of the proposed bill. It also allows us to summarize the bills effect at different geographic levels, including station area, city, and region. We can then both describe individual geographies (e.g., a specific station area) and compare between geographies (e.g., several cities compared individually to the region).

------------------------------------------------------------------------
